### ISSUE TITLE
"JBang - a better Java?" youtube link seems broken

### ISSUE THREAD

**Issue by glefloch** [jbangdev/jbang.dev#36]
Looking at the home page, the link to the video: "JBang - a better Java?" show an error message: "The live event is no longer available". when right clicking the iframe, we can get the link which work but it not an embed link (https://youtu.be/u9mfPW3ydjU). 

When trying to get the embed link from youtube, I have the same url with the same error message.

**Comment by maxandersen** [comment]
hmm - I did see there were issues when I saw the issue come in but now when sitting down and try fix it I don't see any errors and it works for me. I'm going to assume it was a temporary glitch on youtube side.
