### ISSUE TITLE
jbang.dev and jbang.dev/downloads should show most likely command that will work to install

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang.dev#43]
would be great if jbang.dev and jbang.dev/downloads (or maybe even a sticky lightweight banner on every page?) shows the most likely command to install based on the users browser OS.

i.e. on linux/osx provide curl + jbang app setup on on windows the powershell command

...similar on /download page have it choose the default tab based on OS not just the first one.

**Comment by markolo25** [comment]
I'll take this on, working on it on my fork now

**Comment by maxandersen** [comment]
Awesome

**Comment by markolo25** [comment]
This is solved in #44
