### ISSUE TITLE
JBang logo is svg in colour without text

### ISSUE THREAD

**Issue by davsclaus** [jbangdev/jbang.dev#48]
The logo
https://github.com/jbangdev/jbang.dev/blob/main/assets/images/logo.svg

Would it be possible to have it similar to this but in colour
https://github.com/jbangdev/jbang.dev/blob/main/safari-pinned-tab.svg

**Comment by davsclaus** [comment]
We would like to add camel-jbang to the camel projects front page, like the others (scroll a bit down)
https://camel.apache.org/

**Comment by maxandersen** [comment]
iOS client won't Render the svg links so I can't check right now but I'll assume the answer is yes :)

Neither of those in https://github.com/jbangdev/jbang/tree/main/images works for you ?

**Comment by davsclaus** [comment]
Ah perfect I found
https://github.com/jbangdev/jbang/blob/main/images/jbang_icon.svg

I only looked in the website repo
