### ISSUE TITLE
Many JBang catalogs not seen in AppStore anymore

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang.dev#53]
I've noticed many of jbang-catalog repositories available on GitHub do not appear anymore in JBang AppStore.

For example: https://github.com/quarkusio/jbang-catalog, https://github.com/neo4j/jbang-catalog, https://github.com/linux-china/jbang-catalog, https://github.com/grumpyf0x48/jbang-catalog

**Comment by maxandersen** [comment]
I think this is an issue of the script not being resilient to when GitHub api fails. Which it unfortunately often do :/

It needs to be improved.

**Comment by maxandersen** [comment]
just realized we were missing the ratelimithandler ...just added it and lets see how it runs going forward.

**Comment by quintesse** [comment]
That's a nicely simple solution :-)

**Comment by maxandersen** [comment]
Unfortunately it doesn't seem to work/maker a difference :/
